---
title: "Law Commission Reports"
author: "[Reports](index.html) | [Commissions](Law-Commissions.html) | [Chairman](Chairman.html)"
output: 
  html_document:
    css: styles.css
    includes:
      in_header: header.html
      after_body: footer.html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r libraries}
library(dplyr)
library(rvest)
library(DT)
library(glue)
library(stringr)
library(readr)
library(httr)
```

```{r base variables}
reports_base_url <- "http://www.lawcommissionofindia.nic.in/main.htm"
reports_base_xpath <- "/html/body/div/table"
div_p_xpath <- "/html/body/div/p"
lc_details_xpath <- "/html/body/div/table[1]"
update_data <- FALSE
```

```{r Fetch Law Commission details}
if(update_data){
lc_details <- reports_base_url %>% read_html() %>% html_nodes(xpath = lc_details_xpath) %>% html_table() %>% dplyr::bind_rows()
lc_details <- lc_details[,c(1,2)]
lc_details$X1 <- lc_details$X1 %>% stringr::str_to_title() %>% stringr::str_squish()
lc_details$X2[lc_details$X1 == "Sixteenth Law Commission"] <- '2000-2003'
lc_details$X2[lc_details$X1 == "Twentieth Law Commission"] <- '2012-2015'
lc_details$From <- lc_details$X2 %>% stringr::str_extract_all(pattern = "[:digit:]+\\-") %>% unlist() %>% stringr::str_replace_all(pattern = "\\-",replacement = "") %>% stringr::str_squish()
lc_details$To <- lc_details$X2 %>% stringr::str_extract_all(pattern = "\\-[:digit:]+") %>% unlist() %>% stringr::str_replace_all(pattern = "\\-",replacement = "") %>% stringr::str_squish()
lc_details$To[as.numeric(lc_details$To)<100] <- glue("19{lc_details$To[as.numeric(lc_details$To)<100]}")
lc_details$X2 <- NULL
names(lc_details)[] <- c('LC Title','From','To')
write_csv(lc_details, "../data/law-commision-details.csv")
} else {
lc_details <- read_csv("../data/law-commision-details.csv", 
    col_types = cols(From = col_character(), 
        To = col_character()))
}
```

```{r Data Table}
lc_details %>% DT::datatable(
  rownames = FALSE,
  class = 'cell-border stripe',
  escape = FALSE,
  filter = "top",
  options = list(pageLength = 10)
)
```


