---
title: "Law Commission Reports"
author: "Apoorv"
date: "5/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r libraries}
library(dplyr)
library(rvest)
library(DT)
library(glue)
library(stringr)
library(readr)
library(httr)
```

```{r base variables}
reports_base_url <- "http://www.lawcommissionofindia.nic.in/main.htm"
reports_base_xpath <- "/html/body/div/table"
div_p_xpath <- "/html/body/div/p"
lc_details_xpath <- "/html/body/div/table[1]"
```

```{r get report details}
# This is from the above page - reports are structured in different tables with sequential ID's 
all_tables <- seq(5,22)

get_report_details <- function(table_number) {
  table_xpath <- glue("{reports_base_xpath}[{table_number}]")
  table_data <-
    reports_base_url %>% read_html() %>% html_nodes(xpath = table_xpath) %>% html_table()
  table_data <- table_data[[1]]
  table_data[] <- sapply(table_data, as.character)
  return(table_data)
}

all_reports <- lapply(all_tables, get_report_details) %>% bind_rows()

# Clean table
all_reports$X1 <- as.numeric(all_reports$X1)
all_reports <- all_reports[!is.na(all_reports$X1),]
all_reports$X2 <- all_reports$X2 %>% stringr::str_to_title() %>% stringr::str_squish()
names(all_reports)[] <- c('Report ID','Title','Year')

# Fetch reports from 21st LC
lc_21_reports <- data.frame(check.names = FALSE, 
  stringsAsFactors = FALSE,
                `Report ID` = c(263L,264L,265L,266L,267L,
                       268L,269L,270L,271L,272L,273L,274L,275L,276L,277L),
                Title = c("The Protection of Children (Inter-Country Removal and Retention) Bill, 2016",
                       "The Criminal Law (Amendment) Bill, 2017 (Provisions dealing with Food Adulteration)",
                       "Prospects of Exempting Income arising out of Maintenance Money of Minor","Advocates Act",
                       "Hate Speech",
                       "Amendments to Criminal Procedure Code, 1973 – Provisions Relating to Bail | Corrigendum  to 268",
                       "House-keeping of Egg-laying Hens",
                       "Compulsory Registration of Marriages","Human DNA Profiling",
                       "Assessment of Statutory Frameworks of Tribunals in India",
                       "Implementation of United Nations Convention against Torture",
                       "Review of the Contempt of Courts Act, 1971",
                       "LEGAL FRAMEWORK: BCCI vis-à-vis RIGHT TO INFORMATION ACT, 2005",
                       "Legal Framework: Gambling and Sports Betting Including  in Cricket in India",
                       "Wrongful Prosecution (Miscarriage of Justice): Legal Remedies"),
                Year = c(2016L,2017L,2017L,2017L,
                       2017L,2017L,2017L,2017L,2017L,2017L,2017L,2018L,
                       2018L,2018L,2018L) %>% as.character()
)

all_reports <- dplyr::bind_rows(all_reports, lc_21_reports)

```

```{r get chairman details}
all_div_p <- reports_base_url %>% read_html %>% html_nodes(xpath = div_p_xpath) %>% html_text()
list_of_chairman <- all_div_p[grepl(pattern = "\\(chairman",x = all_div_p, ignore.case = TRUE)] %>% stringr::str_squish() %>% stringr::str_replace_all(pattern = "\\(|\\)",replacement = "")
chairman_db <- data.frame('Name'=list_of_chairman)
chairman_db$From <- stringr::str_sub(chairman_db$Name,start = -9,end = -6)
chairman_db$To <- stringr::str_sub(chairman_db$Name,start = -4,end = -1)
chairman_db$Name <- chairman_db$Name %>% stringr::str_replace_all(pattern = "[:digit:]+\\-[:digit:]+",replacement = "") %>% stringr::str_replace_all(pattern = "Chairman",replacement = "") %>% stringr::str_squish()

other_chairman <- data.frame("Name"=c("Mr. Justice P. V. Reddi","Mr. Justice D. K. Jain","Mr. Justice A. P. Shah","Dr. Justice Balbir Singh Chauhan"), "From"=c("2009","2012","2013","2015"), "To"=c("2012","2013","2015","2018"))
chairman_db <- dplyr::bind_rows(chairman_db, other_chairman)
```

```{r Fetch Law Commission details}
lc_details <- reports_base_url %>% read_html() %>% html_nodes(xpath = lc_details_xpath) %>% html_table() %>% dplyr::bind_rows()
lc_details <- lc_details[,c(1,2)]
lc_details$X1 <- lc_details$X1 %>% stringr::str_to_title() %>% stringr::str_squish()
lc_details$X2[lc_details$X1 == "Sixteenth Law Commission"] <- '2000-2003'
lc_details$X2[lc_details$X1 == "Twentieth Law Commission"] <- '2012-2015'
lc_details$From <- lc_details$X2 %>% stringr::str_extract_all(pattern = "[:digit:]+\\-") %>% unlist() %>% stringr::str_replace_all(pattern = "\\-",replacement = "") %>% stringr::str_squish()
lc_details$To <- lc_details$X2 %>% stringr::str_extract_all(pattern = "\\-[:digit:]+") %>% unlist() %>% stringr::str_replace_all(pattern = "\\-",replacement = "") %>% stringr::str_squish()
lc_details$To[as.numeric(lc_details$To)<100] <- glue("19{lc_details$To}")
lc_details$X2 <- NULL
names(lc_details)[] <- c('LC Title','From','To')
```

```{r Detailed table}
lc_links <- read_csv(
  "../data/law-commission-report-links.csv",
  col_types = cols(`Report ID` = col_character())
)

lc_links <- lc_links %>% group_by(`Report ID`) %>% mutate(group_id=row_number())

lc_links <- lc_links[lc_links$group_id == 1,]

all_reports$`Report ID` <- as.character(all_reports$`Report ID`)

view_reports <- left_join(all_reports, lc_links, by=NULL)
view_reports$group_id <- NULL
```

```{r Data Table}
library(kableExtra)

view_reports$URL <- text_spec(view_reports$URL, link = view_reports$URL)

view_reports %>% DT::datatable(
  rownames = FALSE,
  class = 'cell-border stripe',
  escape = FALSE,
  filter = "top",
  options = list(pageLength = 10)
)
```


